[[theme.fontFaces]]
family="Syne"
url="https://fonts.googleapis.com/css2?family=Syne:wght@400..800&display=swap"

[theme]
font = "sans-serif"
headingFont = "Syne"
codeFont = "monospace"
[theme.sidebar]
font = "sans-serif"
headingFont = "Syne"
codeFont = "monospace"
