[server]
enableStaticServing = true

[[theme.fontFaces]]
family="voxel-point"
url="https://www.fontspace.com/voxelpoint-font-f120590"

[theme]
font = "sans-serif"
headingFont = "voxel-point"
codeFont = "monospace"
[theme.sidebar]
font = "sans-serif"
headingFont = "voxel-point"
codeFont = "monospace"
